services:
  weather-app:
    image: weather
    ports:
      - "80:80"
    volumes:
      - ./input:/app/input
      - ./output_image:/app/output_image
      - ./logs:/app/logs
    environment:
      NODE_ENV: production
      STATIC_RESOURCE_PATH: public
      IMAGE_PATH: output_image
      LOG_PATH: logs
      OUTPUT_DIR: output_image
      MODEL_LIST: CMA-GFS,EC
      DEFAULT_MODEL: EC
      IMAGE_NAME: mix.png
      REPORT_HOUR_LIST: 00:00,12:00
      FORCAST_AM_HOUR_LIST: 03:00,06:00,09:00,12:00
      FORCAST_PM_HOUR_LIST: 15:00,18:00,21:00,24:00
      API_URL: /predict
      API_PORT: 5001
      API_HOST: ly-api_app-1
      INPUT_DIR: input
      PORT: 80
      TIME_LEN: 4
      TIME_GAP: 3

  api_app:
    image: api_app
    volumes:
      - ./input:/app/input
      - ./output_image:/app/output_image
    ports:
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  
